[package]
name = "femto"
version = "0.0.1"
authors = ["Dariusz Depta <dariusz@confio.gmbh>"]
description = "Test suites for cw-multi-test"
repository = "https://github.com/DariuszDepta/femto"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["v_0_1_2"]
v_0_1_1 = []
v_0_1_2 = []
v_0_1_3 = []
v_0_1_4 = []
v_1_1_1 = []
v_1_1_2 = []
v_1_1_3 = []
v_1_1_4 = []
v_2 = []

[dependencies]
cosmwasm-std = "1.2.8"
cw-storage-plus = "1.2.0"
cw-utils = "1.0.3"
schemars = "0.8.16"
serde = "1.0.197"

[dev-dependencies]
cw-multi-test = { version = "0.20.0", features = ["cosmwasm_1_2"] }
